use customer_support
select *from customer_shopping_behavior limit 20
-- 1. what is the total revenue generated by male vs female customers?
select Gender,sum(`Purchase Amount (USD)`)
 as revenue 
 from customer_shopping_behavior Group by Gender;
 -- Which customers used a discount but still spent more than the average purchase amount?
alter table customer_shopping_behavior rename column `Purchase Amount (USD)` To Purchase_Amount;
alter table customer_shopping_behavior rename column `Customer ID` To Customer_ID;
alter table customer_shopping_behavior rename column `Discount Applied` To Discount_Applied;
alter table customer_shopping_behavior rename column `Item Purchased` To Item_Purchased;
alter table customer_shopping_behavior rename column `Review Rating` To Review_Rating;
alter table customer_shopping_behavior rename column `Shipping Type` To Shipping_Type ;
alter table customer_shopping_behavior rename column `Subscription Status` To Subscription_Status ;
alter table customer_shopping_behavior rename column  `Previous Purchases` To Previous_Purchases ;
select Customer_ID,  Purchase_Amount from customer_shopping_behavior 
where Discount_Applied ='yes'  and Purchase_Amount >= (select AVG(Purchase_Amount ) from customer_shopping_behavior);
--  What are the top 5 products with the highest average review rating?

select Item_Purchased as " top 5 products",ROUND(avg(Review_Rating ),2) from customer_shopping_behavior group by Item_Purchased
order by avg(Review_Rating) desc
limit 5;
-- 4. compare the average purchase amount between standard and express shipping
select Round(avg(Purchase_Amount),2),Shipping_Type from customer_shopping_behavior
where Shipping_Type in("Express","Standard") Group by Shipping_Type;
-- Do subscribed customers spend more? compare average spend and total revenue between subscribers and non subscribers?
 select Subscription_Status ,
count(Customer_ID),
Round(avg(Purchase_Amount),2)as avg_spend ,
Round(sum(Purchase_Amount),2)as Total_revenue from customer_shopping_behavior
group by Subscription_Status
order by  Total_revenue,avg_spend;

-- 6. Which  5 products have the highest percentage of purchases with discounts applied?

select Item_Purchased ,
Round(
sum(case when 
Discount_Applied = 'yes' Then 1 
Else 0 end)/count(*)*100*2) as discount_rate
from customer_shopping_behavior
group by Item_Purchased
order by  discount_rate DESC 
limit 5;

-- segment customers into new,returning and Loyal based on their  total number of pervious purchases and show the count of each segment

with Customer_Type as (
select Customer_ID,Previous_Purchases,
case
when Previous_Purchases=1 then"new"
when Previous_Purchases Between 2 and 10 then "Returning"
else "Loyal"
end as customer_segment
from customer_shopping_behavior
)
select customer_segment,count(*) as "number of customer" from Customer_Type group  by customer_segment;

-- 8. What are the top 3 most purchased products within each category?

with item_counts as (
select Category,
Item_Purchased,
Count(Customer_ID) as total_orders,
Row_number() over (partition by category order by count(Customer_ID)Desc) as item_rank
from customer_shopping_behavior
group by Category,Item_Purchased)
select item_rank,Category,Item_Purchased,total_orders from item_counts where item_rank <=3;
 -- 9.  Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
 select Subscription_Status,
 count(Customer_ID) as repeat_buyers
 from customer_shopping_behavior  where Previous_Purchases>=5
 group by Subscription_Status;
 
 -- 10. what is the revenue contribution of each age group?
 select Age,
 sum(Purchase_Amount) as total_revenue from customer_shopping_behavior
 group by Age
 order by total_revenue desc;
 